on:
  push:
    branches:
      - staging
      - main # Add the main branch trigger
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4
      - name: ðŸ“¦ Install dependencies
        run: npm install
      - name: ðŸ”¨ Build project for staging
        if: github.ref == 'refs/heads/staging'
        run: |
          export NODE_OPTIONS=--max-old-space-size=4096
          CI=false npm run build-staging
        env:
          NODE_ENV: production # Or adjust this to match your needs
      - name: ðŸ”¨ Build project for main
        if: github.ref == 'refs/heads/main'
        run: |
          export NODE_OPTIONS=--max-old-space-size=4096
          CI=false npm run build
        env:
          NODE_ENV: production
      - name: ðŸ“‚ Sync files via FTP for staging
        if: github.ref == 'refs/heads/staging'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          log-level: verbose
      - name: ðŸ“‚ Sync files via FTP for main
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USERNAME_LIVE}}
          password: ${{ secrets.FTP_PASSWORD_LIVE}}
          local-dir: ./build/
          log-level: verbose
# P3R[MXIDQ9V?
